version: "3.3"

networks:
    aplication-network:
        ipam:
            config:
                - subnet: 172.168.0.0/16

services:
    flask_app:
        build: .
        container_name: flask_run
        ports:
            - '5000:5000'
        networks:
            aplication-network:
                ipv4_address: 172.168.0.5
    
    postgres-server:
        image: postgres
        container_name: flask_db
        environment:
            POSTGRES_PASSWORD: "pedro123"
        ports:
            - '5432:5432'
        volumes:
            - D:/software/docker/data:/var/lib/postgresql/data
        networks:
            aplication-network:
                ipv4_address: 172.168.0.6